jobs:
  include:
    - language: java
      jdk: openjdk11
      services:
      - postgresql
      before_script:
      - createuser companycalendar
      - psql -c "alter user companycalendar with encrypted password 'KkN7{/uvw}?CKi).hDY8YSM0}YMC3QT';" -U postgres
      - psql -c "create database companycalendar;" -U postgres
      - psql -c "grant all privileges on database companycalendar to companycalendar;" -U postgres
      - "cd eta-company-calendar-backend"
      script:
      - "./mvnw clean test -Dspring.profiles.active=travis"
    - stage: test
      name: "Frontend lint"
      language: node_js
      node_js: "12.0"
      cache:
        directories:
          - "node_modules"
      before_script:
      - "cd eta-company-calendar-frontend"
      - "npm install"
      script:
      - "npm run lint"
    - stage: test
      name: "Frontend build"
      language: node_js
      node_js: "12.0"
      cache:
        directories:
          - "node_modules"
      before_script:
      - "cd eta-company-calendar-frontend"
      - "npm install"
      script:
      - "npm run build"

